import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import { FiChevronLeft } from 'react-icons/fi';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export const Layout = ({ children, title }: Readonly<{ title: string, children: React.ReactNode }>) => (
  <div className="container">
    <div className="header">
      <div className="flex text-align-left">
        <Link href="/">
          <FiChevronLeft />
        </Link>
      </div>
      <div className="flex text-align-center">{title}</div>
      <div className="flex"></div>
    </div>
    <div className="content">{children}</div>
  </div>
);